name: Deploy Lambda Function
on:
  push:
    branches:
      - main # Change to your branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your region

      - name: Zip the Lambda function code
        run: zip -r lambda_function.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name my_function \
            --zip-file fileb://lambda_function.zip

      # Extract and display pull request and repository information
      - name: Display PR and Repository Information
        if: github.event_name == 'pull_request'
        run: |
          pr_num=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          repo_name=$(jq -r '.github.repository' "$GITHUB_EVENT_PATH")
          commit_sha=$(jq -r '.pull_request.merge_commit_sha' "$GITHUB_EVENT_PATH")
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Repository Name: ${{ github.repository }}"
          echo "Pull Request SHA: ${{ github.event.pull_request.merge_commit_sha }}"
